version: 2

sources:
  - name: decoded_events
    description:

    database: "{{ env_var('BQ_PUBLIC_DB') }}"
    schema: "{{ env_var('BQ_PUBLIC_SCHEMA') }} "

    tables:
      - name: decoded_events