name: 'blockchain_analysis_transform'
version: '1.0.0'
config-version: 2

profile: 'dbt-bq-dtc'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:       
  - "target"
  - "dbt_modules"

models:

  blockchain_analysis_transform:

    stage:
      +materialized: view
      +schema: stage
      +enabled: true  

vars: 
  start_time: "'2022-09-01 17:00:00'"
  end_time: "'2022-09-01 18:00:00'"